[package]
name = "lepton-markup"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
wasm-bindgen = "0.2.81"
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }